[0m20:33:43.211372 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d3a660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126efed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126efc50>]}


============================== 20:33:43.213918 | e2dfe503-b70e-4cfd-87a5-b2a7e29fa4b0 ==============================
[0m20:33:43.213918 [info ] [MainThread]: Running with dbt=1.8.8
[0m20:33:43.214246 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/maxhilsdorf/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init billboard_hot_100', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:33:43.224665 [debug] [MainThread]: Starter project path: /Users/maxhilsdorf/opt/miniconda3/envs/dbt_billboard/lib/python3.13/site-packages/dbt/include/starter_project
[0m20:33:43.227423 [info ] [MainThread]: 
Your new dbt project "billboard_hot_100" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:33:43.227605 [info ] [MainThread]: Setting up your profile.
[0m20:36:41.669215 [info ] [MainThread]: Profile billboard_hot_100 written to /Users/maxhilsdorf/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m20:36:42.148066 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 178.9682, "process_user_time": 0.673912, "process_kernel_time": 0.135738, "process_mem_max_rss": "116523008", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:36:42.150116 [debug] [MainThread]: Command `dbt init` succeeded at 20:36:42.149913 after 178.97 seconds
[0m20:36:42.150795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11454ad70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110688ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114546ad0>]}
[0m20:36:42.151621 [debug] [MainThread]: Flushing usage events
[0m20:38:39.022737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10503a660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070efed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070efc50>]}


============================== 20:38:39.024939 | e29f3ca2-bd56-4544-badf-f1b86847b36b ==============================
[0m20:38:39.024939 [info ] [MainThread]: Running with dbt=1.8.8
[0m20:38:39.025248 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/maxhilsdorf/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:38:39.033379 [info ] [MainThread]: dbt version: 1.8.8
[0m20:38:39.033605 [info ] [MainThread]: python version: 3.13.0
[0m20:38:39.033743 [info ] [MainThread]: python path: /Users/maxhilsdorf/opt/miniconda3/envs/dbt_billboard/bin/python
[0m20:38:39.033874 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit-Mach-O
[0m20:38:39.149813 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m20:38:39.150124 [info ] [MainThread]: Using profiles dir at /Users/maxhilsdorf/.dbt
[0m20:38:39.150257 [info ] [MainThread]: Using profiles.yml file at /Users/maxhilsdorf/.dbt/profiles.yml
[0m20:38:39.150381 [info ] [MainThread]: Using dbt_project.yml file at /Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml
[0m20:38:39.150507 [info ] [MainThread]: Configuration:
[0m20:38:39.150624 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m20:38:39.150727 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:38:39.150830 [info ] [MainThread]: Required dependencies:
[0m20:38:39.150975 [debug] [MainThread]: Executing "git --help"
[0m20:38:39.168283 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:38:39.168841 [debug] [MainThread]: STDERR: "b''"
[0m20:38:39.169000 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:38:39.169148 [info ] [MainThread]: Connection test skipped since no profile was found
[0m20:38:39.169350 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:38:39.169467 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_core_demo", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m20:38:39.169603 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml> not found

[0m20:38:39.170652 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.17616883, "process_user_time": 0.643277, "process_kernel_time": 0.11285, "process_mem_max_rss": "119816192", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:38:39.170978 [debug] [MainThread]: Command `dbt debug` failed at 20:38:39.170921 after 0.18 seconds
[0m20:38:39.171261 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108900b00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088f95b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086427a0>]}
[0m20:38:39.171579 [debug] [MainThread]: Flushing usage events
[0m20:42:11.429929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e3e660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106defed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106defc50>]}


============================== 20:42:11.432056 | cd35cc2b-caf8-4d4a-8c68-8b21dce8105e ==============================
[0m20:42:11.432056 [info ] [MainThread]: Running with dbt=1.8.8
[0m20:42:11.432363 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/maxhilsdorf/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:42:11.439617 [info ] [MainThread]: dbt version: 1.8.8
[0m20:42:11.439917 [info ] [MainThread]: python version: 3.13.0
[0m20:42:11.440094 [info ] [MainThread]: python path: /Users/maxhilsdorf/opt/miniconda3/envs/dbt_billboard/bin/python
[0m20:42:11.440380 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit-Mach-O
[0m20:42:11.555461 [info ] [MainThread]: Using profiles dir at /Users/maxhilsdorf/.dbt
[0m20:42:11.555752 [info ] [MainThread]: Using profiles.yml file at /Users/maxhilsdorf/.dbt/profiles.yml
[0m20:42:11.555886 [info ] [MainThread]: Using dbt_project.yml file at /Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml
[0m20:42:11.556149 [info ] [MainThread]: adapter type: snowflake
[0m20:42:11.556272 [info ] [MainThread]: adapter version: 1.8.4
[0m20:42:11.556403 [info ] [MainThread]: Configuration:
[0m20:42:11.556512 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m20:42:11.556623 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:42:11.556723 [info ] [MainThread]: Required dependencies:
[0m20:42:11.556863 [debug] [MainThread]: Executing "git --help"
[0m20:42:11.573111 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:42:11.573678 [debug] [MainThread]: STDERR: "b''"
[0m20:42:11.573844 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:42:11.573997 [info ] [MainThread]: Connection:
[0m20:42:11.574161 [info ] [MainThread]:   account: https://lp42590.eu-central-1.snowflakecomputing.com
[0m20:42:11.574275 [info ] [MainThread]:   user: maxhilsdorf
[0m20:42:11.574378 [info ] [MainThread]:   database: BB_DATABASE
[0m20:42:11.574476 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m20:42:11.574573 [info ] [MainThread]:   role: ACCOUNTADMIN
[0m20:42:11.574672 [info ] [MainThread]:   schema: BB_SCHEMA
[0m20:42:11.574774 [info ] [MainThread]:   authenticator: None
[0m20:42:11.574870 [info ] [MainThread]:   oauth_client_id: None
[0m20:42:11.574966 [info ] [MainThread]:   query_tag: None
[0m20:42:11.575063 [info ] [MainThread]:   client_session_keep_alive: False
[0m20:42:11.575161 [info ] [MainThread]:   host: None
[0m20:42:11.575256 [info ] [MainThread]:   port: None
[0m20:42:11.575350 [info ] [MainThread]:   proxy_host: None
[0m20:42:11.575446 [info ] [MainThread]:   proxy_port: None
[0m20:42:11.575541 [info ] [MainThread]:   protocol: None
[0m20:42:11.575634 [info ] [MainThread]:   connect_retries: 1
[0m20:42:11.575727 [info ] [MainThread]:   connect_timeout: None
[0m20:42:11.575821 [info ] [MainThread]:   retry_on_database_errors: False
[0m20:42:11.575913 [info ] [MainThread]:   retry_all: False
[0m20:42:11.576005 [info ] [MainThread]:   insecure_mode: False
[0m20:42:11.576100 [info ] [MainThread]:   reuse_connections: None
[0m20:42:11.576453 [info ] [MainThread]: Registered adapter: snowflake=1.8.4
[0m20:42:11.737305 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m20:42:11.738760 [debug] [MainThread]: Using snowflake connection "debug"
[0m20:42:11.739013 [debug] [MainThread]: On debug: select 1 as id
[0m20:42:11.739232 [debug] [MainThread]: Opening a new connection, currently in state init
[0m20:42:12.787437 [debug] [MainThread]: Snowflake adapter: Error running SQL: select 1 as id
[0m20:42:12.787996 [debug] [MainThread]: Snowflake adapter: Rolling back transaction.
[0m20:42:12.788351 [debug] [MainThread]: On debug: No close available on handle
[0m20:42:12.788688 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m20:42:12.789638 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:42:12.790016 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml> not found

[0m20:42:12.790292 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m20:42:12.792770 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 1.3928325, "process_user_time": 0.67486, "process_kernel_time": 0.125205, "process_mem_max_rss": "123305984", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:42:12.793913 [debug] [MainThread]: Command `dbt debug` failed at 20:42:12.793720 after 1.39 seconds
[0m20:42:12.794467 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m20:42:12.794997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a0de00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a02330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110543df0>]}
[0m20:42:12.795537 [debug] [MainThread]: Flushing usage events
[0m13:07:26.918848 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10716a660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b53ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b53c50>]}


============================== 13:07:26.921505 | 6b4980eb-50a7-4392-ade8-f6090c3f36c5 ==============================
[0m13:07:26.921505 [info ] [MainThread]: Running with dbt=1.8.8
[0m13:07:26.921810 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/maxhilsdorf/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:07:26.922089 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:07:26.929987 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.043225583, "process_user_time": 0.559275, "process_kernel_time": 0.127665, "process_mem_max_rss": "96813056", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m13:07:26.930392 [debug] [MainThread]: Command `dbt run` failed at 13:07:26.930330 after 0.04 seconds
[0m13:07:26.930599 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b75a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088ded50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10885bce0>]}
[0m13:07:26.930760 [debug] [MainThread]: Flushing usage events
[0m22:32:06.261794 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e3e660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124b7ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124b7c50>]}


============================== 22:32:06.264105 | 75411759-c51e-499f-9ae8-8fa97687c510 ==============================
[0m22:32:06.264105 [info ] [MainThread]: Running with dbt=1.8.8
[0m22:32:06.264398 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/maxhilsdorf/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m22:32:06.264664 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/maxhilsdorf/Projekte/fortbildung/dbt_schibsted/data_pipeline_repo/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:32:06.265455 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.03200075, "process_user_time": 0.552144, "process_kernel_time": 0.075879, "process_mem_max_rss": "97026048", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m22:32:06.265729 [debug] [MainThread]: Command `dbt test` failed at 22:32:06.265684 after 0.03 seconds
[0m22:32:06.265896 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124d9a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11207ed50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111ffbce0>]}
[0m22:32:06.266041 [debug] [MainThread]: Flushing usage events
